### ISSUE TITLE
Don't build errors into the grammars

### ISSUE THREAD

**Issue by djalbat** [occam-proof-assistant/Parsers#31]
Have error nodes as non-terminal nodes when no rule parses. And don't treat error nodes any differently with the lazy parser. There's shouldn't be any need, I think. Error tokens, if they remain, should also result in error nodes.

**Comment by ghost** [comment]
There are no error tokens anymore, so that's moot. The lazy parser doesn't now treat error nodes any differently, I can't see now why it should.

**Comment by ghost** [comment]
I really think it's best just to leave errors in the grammar, at least for now.
